version: "2"
services:
  extra_hosts:
    - "postgres:10.132.95.30"
  integracion-bancaria:
    image: "integracion-bancaria:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "45000:5000"
      