version: "2"
services:
  integracion-bancaria:
    extra_hosts:
      postgres: 10.132.95.30
    image: "integracion-bancaria:latest"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "45000:5000"
      